name: Schedule version PRs

on:
  workflow_dispatch:
    inputs:
      shopware_version:
        description: "Shopware version"
        required: true
        type: string

jobs:
  generate-trunk:
    needs: vars
    uses: ./.github/workflows/base_schema.yml
    with:
      shopware_version: ${{ inputs.shopware_version }}
      
  generate-commercial-trunk:
    needs: vars
    uses: ./.github/workflows/plugin_commercial_schema.yml
    with:
      shopware_version: ${{ inputs.shopware_version }}
      
  generate-digitalsalesroom-trunk:
    needs: vars
    uses: ./.github/workflows/plugin_digitalsalesroom_schema.yml
    with:
      shopware_version: ${{ inputs.shopware_version }}
