name: Update Store API

on:
  push:
    branches:
      - 'dx-adhoc/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-schema:
    uses: shopware/docs-ci/.github/workflows/generate_schema.yml@dx-adhoc/add-workflow-for-dsr
    with:
      api_type: storeapi
      plugin_name: SwagGuidedShopping
      plugin_url: gitlab.shopware.com:shopware/6/services/swagguidedshopping.git
    secrets: inherit
        
  open-pr:
    name: "Open a pull request"
    runs-on: ubuntu-latest
    needs: [generate-schema]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: download api schema
      uses: actions/download-artifact@v3
      with:
        name: ${{needs.generate-schema.outputs.api_schema}}

    - name: install yq
      uses: cachix/install-nix-action@v18

    - name: Prettify
      run: |
        sudo apt-get update
        sudo apt-get install -y moreutils
        jq . storeapi.json | sponge storeapi.json
      
    - name: Create DSR PR
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: SwagGuidedShopping-storeapi.json
        author: shopwareBot <example@example.com>
        committer: shopwareBot <example@example.com>
        assignees: Isengo1989
        branch: dsr-schema-update
        delete-branch: true
        title: 'Update DSR store API schema'
